# Generated by Django 5.2.6 on 2025-12-12 00:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambioFuente',
            fields=[
                ('id_fuente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la fuente (ej: ExchangeRate API, Banco Central Chile)', max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código único de la fuente', max_length=50, unique=True)),
                ('url_api', models.URLField(blank=True, help_text='URL base de la API', null=True)),
                ('api_key', models.CharField(blank=True, help_text='API Key si es necesario', max_length=255, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la fuente está activa')),
                ('orden_prioridad', models.IntegerField(default=0, help_text='Orden de prioridad (menor número = mayor prioridad)')),
                ('ultima_consulta_exitosa', models.DateTimeField(blank=True, null=True)),
                ('ultima_consulta_fallida', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0, help_text='Contador de intentos fallidos consecutivos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente de Tipo de Cambio',
                'verbose_name_plural': 'Fuentes de Tipo de Cambio',
                'db_table': 'tipo_cambio_fuente',
                'ordering': ['orden_prioridad', 'codigo'],
                'indexes': [models.Index(fields=['activa', 'orden_prioridad'], name='tipo_cambio_fuente_activa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id_tipo_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('moneda_origen', models.CharField(help_text='Código ISO de moneda origen (ej: USD)', max_length=3)),
                ('moneda_destino', models.CharField(help_text='Código ISO de moneda destino (ej: CLP)', max_length=3)),
                ('tasa', models.DecimalField(decimal_places=8, help_text='Tasa de cambio', max_digits=20)),
                ('fecha', models.DateField(help_text='Fecha del tipo de cambio')),
                ('vigente_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_fuente', models.ForeignKey(db_column='id_fuente', on_delete=django.db.models.deletion.RESTRICT, related_name='tipos_cambio', to='microservicio.tipocambiofuente')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'db_table': 'tipo_cambio',
                'indexes': [models.Index(fields=['moneda_origen', 'moneda_destino', 'fecha'], name='tipo_cambio_monedas_fecha_idx'), models.Index(fields=['vigente_desde', 'vigente_hasta'], name='tipo_cambio_vigencia_idx')],
                'unique_together': {('id_fuente', 'moneda_origen', 'moneda_destino', 'fecha')},
            },
        ),
    ]
