# Generated by Django 5.2.6 on 2025-11-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(choices=[('CALIFICACION', 'Calificación'), ('CARGA', 'Carga'), ('CARGA_DETALLE', 'Carga Detalle'), ('INSTRUMENTO', 'Instrumento'), ('USUARIO', 'Usuario'), ('OTRA', 'Otra')], max_length=30)),
                ('entidad_id', models.BigIntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(blank=True, max_length=50, null=True)),
                ('valores_antes', models.JSONField(blank=True, null=True)),
                ('valores_despues', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actor_id', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria',
                'indexes': [models.Index(fields=['actor_id'], name='auditoria_actor_i_847d5a_idx'), models.Index(fields=['entidad', 'entidad_id'], name='auditoria_entidad_9c3bf7_idx'), models.Index(fields=['fecha'], name='auditoria_fecha_b71d64_idx')],
            },
        ),
    ]
