# Generated by Django 5.2.6 on 2025-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha', '-id_auditoria'], 'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
    ]
