# Generated by Django 5.2.6 on 2025-11-13 04:07

import auditoria.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_auditoria_options'),
        ('usuarios', '0002_usuario_usuario_usernam_284c68_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='valores_antes',
            field=auditoria.fields.OracleJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='valores_despues',
            field=auditoria.fields.OracleJSONField(blank=True, null=True),
        ),
        # NOTA: Estos índices también existen en cretable_oracle (líneas 409-411)
        # - actor_id: ix_aud_actor (línea 409)
        # - (entidad, entidad_id): ix_aud_entidad (línea 410)
        # - fecha: ix_aud_fecha (línea 411)
        # Si usas cretable_oracle primero, estos AddIndex fallarán con ORA-01408
        # IMPORTANTE: Si obtienes ORA-01408 al usar Método 1 (solo migrate), significa que Oracle
        # ya creó los índices automáticamente (por FK, UNIQUE, o por ejecución previa de migrate).
        # Solución: COMENTAR estas líneas para evitar ORA-01408
        # Si los índices NO existen y necesitas crearlos, descomenta estas líneas:
        # migrations.AddIndex(
        #     model_name='auditoria',
        #     index=models.Index(fields=['actor_id'], name='auditoria_actor_i_847d5a_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='auditoria',
        #     index=models.Index(fields=['entidad', 'entidad_id'], name='auditoria_entidad_9c3bf7_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='auditoria',
        #     index=models.Index(fields=['fecha'], name='auditoria_fecha_b71d64_idx'),
        # ),
    ]
    