# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_create_indexes_entidad_fecha'),
        ('usuarios', '0004_usuariorol_usuario_rol_id_rol_52d79a_idx'),
    ]

    operations = [
        # Los índices ya fueron creados por la migración 0004_create_indexes_entidad_fecha usando RunSQL
        # Esta migración queda vacía porque los índices ya existen
        # Si necesitas crearlos de nuevo, descomenta los AddIndex de abajo
        # migrations.AddIndex(
        #     model_name='auditoria',
        #     index=models.Index(fields=['actor_id'], name='auditoria_actor_i_847d5a_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='auditoria',
        #     index=models.Index(fields=['entidad', 'entidad_id'], name='auditoria_entidad_9c3bf7_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='auditoria',
        #     index=models.Index(fields=['fecha'], name='auditoria_fecha_b71d64_idx'),
        # ),
    ]
