# Generated by Django 5.2.6 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_auditoria_auditoria_actor_i_847d5a_idx_and_more'),
        ('usuarios', '0005_usuariorol_ix_usuario_rol_rol'),
    ]

    operations = [
        # COMENTADO: Oracle crea automáticamente índice para Foreign Key actor_id
        # El índice AUDITORIA_ACTOR_ID_D934B5BF ya existe
        # migrations.AddIndex(
        #     model_name='auditoria',
        #     index=models.Index(fields=['actor_id'], name='ix_aud_actor'),
        # ),
        # Estos índices SÍ se crean porque NO son Foreign Keys
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['entidad', 'entidad_id'], name='ix_aud_entidad'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['fecha'], name='ix_aud_fecha'),
        ),
    ]
