# Generated by Django 5.2.6 on 2025-11-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id_fuente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'db_table': 'fuente',
                'indexes': [models.Index(fields=['codigo'], name='fuente_codigo_f64eab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('decimales', models.SmallIntegerField(default=2)),
                ('vigente', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'moneda',
                'indexes': [models.Index(fields=['codigo'], name='moneda_codigo_4eae98_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
                'indexes': [models.Index(fields=['codigo'], name='pais_codigo_945e69_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonedaPais',
            fields=[
                ('id_moneda_pais', models.AutoField(primary_key=True, serialize=False)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.CASCADE, to='core.moneda')),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
            options={
                'verbose_name': 'Moneda por País',
                'verbose_name_plural': 'Monedas por País',
                'db_table': 'moneda_pais',
                'indexes': [models.Index(fields=['id_moneda', 'id_pais'], name='moneda_pais_id_mone_588c2e_idx'), models.Index(fields=['id_pais'], name='moneda_pais_id_pais_8a7ff2_idx')],
                'unique_together': {('id_moneda', 'id_pais')},
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id_mercado', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.RESTRICT, to='core.pais')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'mercado',
                'indexes': [models.Index(fields=['codigo'], name='mercado_codigo_dbac3e_idx'), models.Index(fields=['id_pais'], name='mercado_id_pais_86cfe6_idx')],
            },
        ),
    ]
