# Generated by Django 5.2.6 on 2025-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'ordering': ['codigo'], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['codigo'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
