# Generated by Django 5.2.6 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_moneda_options_alter_pais_options'),
    ]

    operations = [
        # TODOS los índices comentados porque Oracle ya los creó automáticamente:
        # - Campos UNIQUE → Oracle crea índices únicos automáticamente
        # - Foreign Keys → Oracle puede crear índices automáticamente
        # - unique_together → Oracle crea índices únicos automáticamente
        # Si necesitas estos índices y NO existen, descomenta las líneas correspondientes
        # migrations.AddIndex(
        #     model_name='fuente',
        #     index=models.Index(fields=['codigo'], name='fuente_codigo_f64eab_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='mercado',
        #     index=models.Index(fields=['codigo'], name='mercado_codigo_dbac3e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='mercado',
        #     index=models.Index(fields=['id_pais'], name='mercado_id_pais_86cfe6_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='moneda',
        #     index=models.Index(fields=['codigo'], name='moneda_codigo_4eae98_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='monedapais',
        #     index=models.Index(fields=['id_moneda', 'id_pais'], name='moneda_pais_id_mone_588c2e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='monedapais',
        #     index=models.Index(fields=['id_pais'], name='moneda_pais_id_pais_8a7ff2_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='pais',
        #     index=models.Index(fields=['codigo'], name='pais_codigo_945e69_idx'),
        # ),
    ]
