# Generated by Django 5.2.6 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mercado_mercado_id_pais_86cfe6_idx_and_more'),
    ]

    operations = [
        # COMENTADO: Oracle crea automáticamente índices para Foreign Keys
        # Estos índices ya existen automáticamente en Oracle
        # migrations.AddIndex(
        #     model_name='mercado',
        #     index=models.Index(fields=['id_pais'], name='ix_mercado_pais'),
        # ),
        # migrations.AddIndex(
        #     model_name='monedapais',
        #     index=models.Index(fields=['id_pais'], name='ix_moneda_pais_pais'),
        # ),
    ]
