# Generated by Django 5.2.6 on 2025-11-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mercado_ix_mercado_pais_and_more'),
    ]

    operations = [
        # COMENTADO: Estos índices nunca se crearon porque las migraciones anteriores
        # estaban comentadas. Oracle crea automáticamente índices para Foreign Keys
        # con nombres diferentes, por lo que no hay nada que remover.
        # migrations.RemoveIndex(
        #     model_name='mercado',
        #     name='ix_mercado_pais',
        # ),
        # migrations.RemoveIndex(
        #     model_name='monedapais',
        #     name='ix_moneda_pais_pais',
        # ),
    ]
