"""
Django settings for proyecto_nuam project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iwt#5dsz2f7^_txuo@ivsf&ax9_@ai4&d(9pl3ji*(xra0*udx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Configuración de Sentry (monitoreo de errores) - Opcional
# Para habilitar: Configura SENTRY_DSN en .env o descomenta y agrega tu DSN
SENTRY_DSN = config('SENTRY_DSN', default=None)
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.logging import LoggingIntegration
        
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(transaction_style='url'),
                LoggingIntegration(level=None, event_level=None),
            ],
            traces_sample_rate=1.0 if DEBUG else 0.1,  # 100% en desarrollo, 10% en producción
            send_default_pii=True,  # Enviar información personal identificable
            environment='development' if DEBUG else 'production',
        )
    except ImportError:
        # sentry-sdk no está instalado, continuar sin Sentry
        pass

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'nuam.local']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # Apps NUAM organizadas en orden lógico de uso
    'usuarios',        # 1. Usuarios y Permisos
    'core',            # 2. Catálogos Base
    'corredoras',      # 3. Corredoras
    'instrumentos',    # 4. Instrumentos
    'calificaciones',  # 5. Calificaciones Tributarias
    'cargas',          # 6. Cargas Masivas
    'auditoria',       # 7. Auditoría
    'api',             # API REST
    'microservicio',   # 8. Microservicios (Gráficos, Tipos de Cambio)
]

# Agregar django_extensions si está instalado (opcional, solo necesario para HTTPS con runserver_plus)
try:
    import django_extensions
    INSTALLED_APPS.append('django_extensions')
except ImportError:
    pass  # django_extensions no está instalado, no es crítico para el funcionamiento básico

# Agregar drf_spectacular si está instalado (opcional, para Swagger/OpenAPI)
try:
    import drf_spectacular
    INSTALLED_APPS.append('drf_spectacular')
except ImportError:
    pass  # drf_spectacular no está instalado, Swagger/OpenAPI no estará disponible

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_nuam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.user_info',  # Información del usuario (roles, nombre, email)
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_nuam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ============================================================
# CONFIGURACIÓN DE BASE DE DATOS
# ============================================================
# 
# INSTRUCCIONES PARA USAR ORACLE:
# 1. Comenta el bloque DATABASES de SQLite (líneas 94-99)
# 2. Descomenta el bloque DATABASES de Oracle (líneas 102-110)
# 3. Asegúrate de tener Oracle Database 23c Free instalado
# 4. Verifica las credenciales en la configuración Oracle
# 5. Ejecuta: python manage.py migrate
#
# ============================================================

# Configuración SQLite (por defecto para desarrollo rápido)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Configuración Oracle Database 23c Free
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': config('DB_NAME', default='127.0.0.1:1521/FREEPDB1'),  # Formato Easy Connect
        'USER': config('DB_USER', default='nuam'),
        'PASSWORD': config('DB_PASSWORD', default='nuam_pwd'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Authentication URLs
LOGIN_REDIRECT_URL = '/'  # Redirige a home después del login
LOGOUT_REDIRECT_URL = '/accounts/login/'  # Redirige a login después del logout
LOGIN_URL = '/accounts/login/'  # URL para el login


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'templates' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Images, Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Permite GET sin autenticación, POST/PUT/DELETE requieren auth
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# Swagger/OpenAPI Schema (solo si drf_spectacular está instalado)
try:
    import drf_spectacular
    REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS'] = 'drf_spectacular.openapi.AutoSchema'
    
    # drf-spectacular settings (Swagger/OpenAPI)
    SPECTACULAR_SETTINGS = {
        'TITLE': 'NUAM API',
        'DESCRIPTION': 'API REST para Sistema de Calificaciones Tributarias',
        'VERSION': '1.0.0',
        'SERVE_INCLUDE_SCHEMA': False,
        'COMPONENT_SPLIT_REQUEST': True,
        'SCHEMA_PATH_PREFIX': '/api/',
    }
except ImportError:
    pass  # drf_spectacular no está instalado, Swagger no estará disponible

# ============================================================
# CONFIGURACIÓN DE APACHE PULSAR
# ============================================================
PULSAR_SERVICE_URL = config('PULSAR_SERVICE_URL', default='pulsar://localhost:6650')
PULSAR_ADMIN_URL = config('PULSAR_ADMIN_URL', default='http://localhost:8080')

# Topics de Pulsar para microservicios NUAM
PULSAR_TOPICS = {
    'tipo_cambio': 'persistent://public/default/nuam-tipo-cambio',
    'carga_masiva': 'persistent://public/default/nuam-carga-masiva',
    'enriquecimiento_datos': 'persistent://public/default/nuam-enriquecimiento',
    'actualizacion_graficos': 'persistent://public/default/nuam-actualizacion-graficos',
    'comprobante_generado': 'persistent://public/default/nuam-comprobante-generado',
}

# Configuración del cliente Pulsar
PULSAR_ENABLED = config('PULSAR_ENABLED', default=True, cast=bool)
PULSAR_OPERATION_TIMEOUT = config('PULSAR_OPERATION_TIMEOUT', default=30, cast=int)  # segundos

# CONFIGURACIÓN DE TIPOS DE CAMBIO
# Si está habilitado, intentará obtener tipos de cambio automáticamente al iniciar Django
# si no hay tipos de cambio recientes (últimas 24 horas)
# Recomendado: False (usar cron/tarea programada en su lugar)
OBTENER_TIPOS_CAMBIO_AUTOMATICO = config('OBTENER_TIPOS_CAMBIO_AUTOMATICO', default=False, cast=bool)

# CONFIGURACIÓN DE PULSAR TOPICS
# Si está habilitado, creará automáticamente los topics de Pulsar al iniciar Django
# si no existen. En Pulsar standalone, los topics se crean automáticamente al publicar
# el primer mensaje, pero este flag permite crearlos explícitamente al inicio.
# Recomendado: True (para asegurar que los topics existan)
CREAR_TOPICS_PULSAR_AUTOMATICO = config('CREAR_TOPICS_PULSAR_AUTOMATICO', default=True, cast=bool)

# Microservicio de Generación de Documentos
MICROSERVICIO_DOCS_URL = config('MICROSERVICIO_DOCS_URL', default='http://localhost:5001')

# ============================================================
# CONFIGURACIÓN SSL/HTTPS
# ============================================================

# Rutas a los certificados (relativas a BASE_DIR)
SSL_CERTIFICATE = BASE_DIR / 'Certificado' / 'server.crt'
SSL_PRIVATE_KEY = BASE_DIR / 'Certificado' / 'server.key'

# Configuración de seguridad HTTPS
# En desarrollo, permitir HTTP pero mostrar advertencias
# En producción, forzar HTTPS
if not DEBUG:
    # Configuración para producción
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Configuración para desarrollo
    # Permitir HTTP en desarrollo, pero se puede usar HTTPS con runserver_plus
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
