# Generated by Django 5.2.6 on 2025-11-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('core', '0001_initial'),
        ('corredoras', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id_carga', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('masiva', 'Masiva')], max_length=20)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('filas_total', models.IntegerField(default=0)),
                ('insertados', models.IntegerField(default=0)),
                ('actualizados', models.IntegerField(default=0)),
                ('rechazados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('validando', 'Validando'), ('importando', 'Importando'), ('reconciliando', 'Reconciliando'), ('done', 'Completada'), ('failed', 'Fallida')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuario')),
                ('id_corredora', models.ForeignKey(db_column='id_corredora', on_delete=django.db.models.deletion.RESTRICT, to='corredoras.corredora')),
                ('id_fuente', models.ForeignKey(db_column='id_fuente', on_delete=django.db.models.deletion.RESTRICT, to='core.fuente')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'db_table': 'carga',
            },
        ),
        migrations.CreateModel(
            name='CargaDetalle',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('linea', models.IntegerField()),
                ('estado_linea', models.CharField(choices=[('ok', 'OK'), ('rechazo', 'Rechazo')], max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('hash_linea', models.CharField(blank=True, max_length=64, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_calificacion', models.ForeignKey(blank=True, db_column='id_calificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.calificacion')),
                ('id_carga', models.ForeignKey(db_column='id_carga', on_delete=django.db.models.deletion.CASCADE, to='cargas.carga')),
            ],
            options={
                'verbose_name': 'Detalle Carga',
                'verbose_name_plural': 'Detalles Cargas',
                'db_table': 'carga_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['id_corredora'], name='carga_id_corr_67282b_idx'),
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['id_fuente'], name='carga_id_fuen_0edfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['creado_por'], name='carga_creado__755dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['estado'], name='carga_estado_8b424f_idx'),
        ),
        migrations.AddIndex(
            model_name='cargadetalle',
            index=models.Index(fields=['id_carga'], name='carga_detal_id_carg_1b5872_idx'),
        ),
        migrations.AddIndex(
            model_name='cargadetalle',
            index=models.Index(fields=['id_carga', 'linea'], name='carga_detal_id_carg_ccfb76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cargadetalle',
            unique_together={('id_carga', 'hash_linea'), ('id_carga', 'linea')},
        ),
    ]
