# Generated by Django 5.2.6 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_calificacion_calificacio_id_corr_1bc757_idx_and_more'),
        ('cargas', '0001_initial'),
        ('core', '0003_fuente_fuente_codigo_f64eab_idx_and_more'),
        ('corredoras', '0001_initial'),
        ('usuarios', '0003_create_index_id_rol'),
    ]

    operations = [
        # TODOS los índices comentados porque Oracle ya los creó automáticamente:
        # - Foreign Keys → Oracle puede crear índices automáticamente
        # Si necesitas estos índices y NO existen, descomenta las líneas correspondientes
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['id_corredora'], name='carga_id_corr_67282b_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['id_fuente'], name='carga_id_fuen_0edfbe_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['creado_por'], name='carga_creado__755dcc_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['estado'], name='carga_estado_8b424f_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='cargadetalle',
        #     index=models.Index(fields=['id_carga'], name='carga_detal_id_carg_1b5872_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='cargadetalle',
        #     index=models.Index(fields=['id_carga', 'linea'], name='carga_detal_id_carg_ccfb76_idx'),
        # ),
    ]
