# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_calificacion_calificacio_id_corr_1bc757_idx_and_more'),
        ('cargas', '0002_carga_carga_id_corr_67282b_idx_and_more'),
        ('core', '0004_mercado_mercado_id_pais_86cfe6_idx_and_more'),
        ('corredoras', '0003_corredora_corredora_nombre_c2ee43_idx_and_more'),
        ('usuarios', '0004_usuariorol_usuario_rol_id_rol_52d79a_idx'),
    ]

    operations = [
        # Índices de Foreign Keys comentados porque ya existen en la base de datos.
        # Solo se mantiene el índice de 'estado' que es un campo normal.
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['estado'], name='carga_estado_8b424f_idx'),
        ),
    ]
