# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_calificacion_calificacio_id_corr_1bc757_idx_and_more'),
        ('cargas', '0002_carga_carga_id_corr_67282b_idx_and_more'),
        ('core', '0004_mercado_mercado_id_pais_86cfe6_idx_and_more'),
        ('corredoras', '0003_corredora_corredora_nombre_c2ee43_idx_and_more'),
        ('usuarios', '0004_usuariorol_usuario_rol_id_rol_52d79a_idx'),
    ]

    operations = [
        # NOTA: Si obtienes ORA-01408 o ORA-00955 al ejecutar migrate, significa que el índice ya existe
        # En ese caso, comenta el AddIndex correspondiente y vuelve a ejecutar migrate
        # Para usuarios nuevos (BD desde cero), estos índices se crearán automáticamente
        # COMENTADOS: Estos índices ya existen en Oracle (probablemente porque Oracle los creó automáticamente para Foreign Keys)
        # Si tu base de datos es nueva y obtienes ORA-01408, descomenta estos AddIndex
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['id_corredora'], name='carga_id_corr_67282b_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['id_fuente'], name='carga_id_fuen_0edfbe_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['creado_por'], name='carga_creado__755dcc_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
        migrations.AddIndex(
            model_name='carga',
            index=models.Index(fields=['estado'], name='carga_estado_8b424f_idx'),
        ),  # MANTENER: Campo normal (no Foreign Key) - Oracle no lo crea automáticamente
        # migrations.AddIndex(
        #     model_name='cargadetalle',
        #     index=models.Index(fields=['id_carga'], name='carga_detal_id_carg_1b5872_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
    ]
