# Generated by Django 5.2.6 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_calificacion_ix_calif_corr_and_more'),
        ('cargas', '0003_carga_carga_id_corr_67282b_idx_and_more'),
        ('core', '0005_mercado_ix_mercado_pais_and_more'),
        ('corredoras', '0004_corredora_ix_corredora_pais_and_more'),
        ('usuarios', '0005_usuariorol_ix_usuario_rol_rol'),
    ]

    operations = [
        # COMENTADO: Oracle crea automáticamente índices para Foreign Keys
        # Estos índices ya existen automáticamente en Oracle
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['id_corredora'], name='ix_carga_corr'),
        # ),
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['id_fuente'], name='ix_carga_fuen'),
        # ),
        # migrations.AddIndex(
        #     model_name='carga',
        #     index=models.Index(fields=['creado_por'], name='ix_carga_user'),
        # ),
        # migrations.AddIndex(
        #     model_name='cargadetalle',
        #     index=models.Index(fields=['id_carga'], name='ix_cd_carga'),
        # ),
    ]
