# Generated by Django 5.2.6 on 2025-11-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0004_carga_ix_carga_corr_carga_ix_carga_fuen_and_more'),
    ]

    operations = [
        # COMENTADO: Estos índices nunca se crearon porque las migraciones anteriores
        # estaban comentadas. Oracle crea automáticamente índices para Foreign Keys
        # con nombres diferentes, por lo que no hay nada que remover.
        # migrations.RemoveIndex(
        #     model_name='carga',
        #     name='ix_carga_corr',
        # ),
        # migrations.RemoveIndex(
        #     model_name='carga',
        #     name='ix_carga_fuen',
        # ),
        # migrations.RemoveIndex(
        #     model_name='carga',
        #     name='ix_carga_user',
        # ),
        # migrations.RemoveIndex(
        #     model_name='cargadetalle',
        #     name='ix_cd_carga',
        # ),
    ]
