# Generated by Django 5.2.6 on 2025-11-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0005_remove_carga_ix_carga_corr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomologacionCampo',
            fields=[
                ('id_homologacion', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(blank=True, help_text='Código del formato origen', max_length=10, null=True)),
                ('certificado', models.CharField(blank=True, help_text='Código del certificado', max_length=10, null=True)),
                ('campo_origen', models.CharField(blank=True, help_text='Nombre del campo en el origen', max_length=120, null=True)),
                ('campo_destino', models.CharField(blank=True, help_text='Nombre del campo destino', max_length=120, null=True)),
                ('transform', models.CharField(blank=True, help_text='Regla de transformación a aplicar', max_length=200, null=True)),
                ('obligatorio', models.BooleanField(default=False, help_text='Indica si el campo es obligatorio')),
                ('vigente_desde', models.DateField(blank=True, help_text='Fecha desde la cual es válida la homologación', null=True)),
                ('vigente_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual es válida la homologación', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homologación Campo',
                'verbose_name_plural': 'Homologaciones Campos',
                'db_table': 'homologacion_campo',
                'ordering': ['origen', 'certificado', 'campo_origen'],
                'indexes': [models.Index(fields=['origen', 'certificado'], name='homologacio_origen_7b2b24_idx'), models.Index(fields=['vigente_desde', 'vigente_hasta'], name='homologacio_vigente_93cf47_idx')],
            },
        ),
    ]
