# Generated by Django 5.2.6 on 2025-11-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        # Índices comentados porque:
        # 1. username es UNIQUE en Oracle (línea 101 de cretable_oracle), Oracle crea automáticamente un índice único
        # 2. id_persona ya tiene índice ix_usuario_persona (línea 111 de cretable_oracle)
        # 3. usuario_rol tiene UNIQUE constraint en (id_usuario, id_rol) (línea 130 de cretable_oracle), Oracle crea índice automático
        # Crear estos índices manualmente causa error ORA-01408: "esta lista de columnas ya está indexada"
        # migrations.AddIndex(
        #     model_name='usuario',
        #     index=models.Index(fields=['username'], name='usuario_usernam_284c68_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuario',
        #     index=models.Index(fields=['id_persona'], name='usuario_id_pers_702c68_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariorol',
        #     index=models.Index(fields=['id_usuario', 'id_rol'], name='usuario_rol_id_usua_517075_idx'),
        # ),
        # NOTA: Este índice también existe en cretable_oracle (línea 132) como ix_usuario_rol_rol
        # Si usas cretable_oracle primero, este AddIndex fallará con ORA-01408
        # IMPORTANTE: Si obtienes ORA-01408 al usar Método 1 (solo migrate), significa que Oracle
        # ya creó el índice automáticamente (por FK o por ejecución previa de migrate).
        # Solución: COMENTAR esta línea para evitar ORA-01408
        # Si el índice NO existe y necesitas crearlo, descomenta esta línea:
        # migrations.AddIndex(
        #     model_name='usuariorol',
        #     index=models.Index(fields=['id_rol'], name='usuario_rol_id_rol_52d79a_idx'),
        # ),
    ]
