# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_create_index_id_rol'),
    ]

    operations = [
        # El índice id_rol ya fue creado por la migración 0003_create_index_id_rol usando RunSQL
        # Esta migración queda vacía porque el índice ya existe
        # Si necesitas crearlo de nuevo, descomenta el AddIndex de abajo
        # migrations.AddIndex(
        #     model_name='usuariorol',
        #     index=models.Index(fields=['id_rol'], name='usuario_rol_id_rol_52d79a_idx'),
        # ),
    ]
