# Generated by Django 5.2.6 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuariorol_usuario_rol_id_rol_52d79a_idx'),
    ]

    operations = [
        # COMENTADO: Oracle crea automáticamente índice para Foreign Key id_rol
        # El índice USUARIO_ROL_ID_ROL_5FB37218 ya existe
        # migrations.AddIndex(
        #     model_name='usuariorol',
        #     index=models.Index(fields=['id_rol'], name='ix_usuario_rol_rol'),
        # ),
    ]
