# Generated by Django 5.2.6 on 2025-11-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredora',
            fields=[
                ('id_corredora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.RESTRICT, to='core.pais')),
            ],
            options={
                'verbose_name': 'Corredora',
                'verbose_name_plural': 'Corredoras',
                'db_table': 'corredora',
            },
        ),
        migrations.CreateModel(
            name='CorredoraIdentificador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=30)),
                ('es_principal', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_corredora', models.ForeignKey(db_column='id_corredora', on_delete=django.db.models.deletion.CASCADE, to='corredoras.corredora')),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.RESTRICT, to='core.pais')),
            ],
            options={
                'verbose_name': 'Identificador Corredora',
                'verbose_name_plural': 'Identificadores Corredoras',
                'db_table': 'corredora_identificador',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCorredora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_corredora', models.ForeignKey(db_column='id_corredora', on_delete=django.db.models.deletion.RESTRICT, to='corredoras.corredora')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Corredora',
                'verbose_name_plural': 'Usuario Corredoras',
                'db_table': 'usuario_corredora',
            },
        ),
        # migrations.AddIndex(
        #     model_name='corredora',
        #     index=models.Index(fields=['nombre'], name='corredora_nombre_c2ee43_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='corredora',
        #     index=models.Index(fields=['id_pais'], name='corredora_id_pais_4a9ecc_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='corredoraidentificador',
        #     index=models.Index(fields=['tipo', 'numero', 'id_pais'], name='corredora_i_tipo_6b3d72_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='corredoraidentificador',
        #     index=models.Index(fields=['id_corredora'], name='corredora_i_id_corr_531e3e_idx'),
        # ),
        migrations.AlterUniqueTogether(
            name='corredoraidentificador',
            unique_together={('tipo', 'numero', 'id_pais')},
        ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_usuario', 'id_corredora'], name='usuario_cor_id_usua_d9a998_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_usuario'], name='usuario_cor_id_usua_6ed4c8_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_corredora'], name='usuario_cor_id_corr_b32be7_idx'),
        # ),
        migrations.AlterUniqueTogether(
            name='usuariocorredora',
            unique_together={('id_usuario', 'id_corredora')},
        ),
    ]
