# Generated by Django 5.2.6 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fuente_fuente_codigo_f64eab_idx_and_more'),
        ('corredoras', '0001_initial'),
        ('usuarios', '0003_create_index_id_rol'),
    ]

    operations = [
        # TODOS los índices comentados porque Oracle ya los creó automáticamente:
        # - Foreign Keys → Oracle puede crear índices automáticamente
        # - unique_together → Oracle crea índices únicos automáticamente
        # Si necesitas estos índices y NO existen, descomenta las líneas correspondientes
        # migrations.AddIndex(
        #     model_name='corredora',
        #     index=models.Index(fields=['nombre'], name='corredora_nombre_c2ee43_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='corredora',
        #     index=models.Index(fields=['id_pais'], name='corredora_id_pais_4a9ecc_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='corredoraidentificador',
        #     index=models.Index(fields=['tipo', 'numero', 'id_pais'], name='corredora_i_tipo_6b3d72_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='corredoraidentificador',
        #     index=models.Index(fields=['id_corredora'], name='corredora_i_id_corr_531e3e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_usuario', 'id_corredora'], name='usuario_cor_id_usua_d9a998_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_usuario'], name='usuario_cor_id_usua_6ed4c8_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_corredora'], name='usuario_cor_id_corr_b32be7_idx'),
        # ),
    ]
