# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mercado_mercado_id_pais_86cfe6_idx_and_more'),
        ('corredoras', '0002_corredora_corredora_nombre_c2ee43_idx_and_more'),
        ('usuarios', '0004_usuariorol_usuario_rol_id_rol_52d79a_idx'),
    ]

    operations = [
        # NOTA: Si obtienes ORA-01408 o ORA-00955 al ejecutar migrate, significa que el índice ya existe
        # En ese caso, comenta el AddIndex correspondiente y vuelve a ejecutar migrate
        # Para usuarios nuevos (BD desde cero), estos índices se crearán automáticamente
        # COMENTADOS: Estos índices ya existen en Oracle (probablemente porque Oracle los creó automáticamente para Foreign Keys)
        # Si tu base de datos es nueva y obtienes ORA-01408, descomenta estos AddIndex
        migrations.AddIndex(
            model_name='corredora',
            index=models.Index(fields=['nombre'], name='corredora_nombre_c2ee43_idx'),
        ),  # MANTENER: Campo normal (no Foreign Key) - Oracle no lo crea automáticamente
        # migrations.AddIndex(
        #     model_name='corredora',
        #     index=models.Index(fields=['id_pais'], name='corredora_id_pais_4a9ecc_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
        # migrations.AddIndex(
        #     model_name='corredoraidentificador',
        #     index=models.Index(fields=['id_corredora'], name='corredora_i_id_corr_531e3e_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_usuario'], name='usuario_cor_id_usua_6ed4c8_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_corredora'], name='usuario_cor_id_corr_b32be7_idx'),
        # ),  # COMENTADO: El índice ya existe en Oracle (ORA-01408) - Foreign Key
    ]
