# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mercado_mercado_id_pais_86cfe6_idx_and_more'),
        ('corredoras', '0002_corredora_corredora_nombre_c2ee43_idx_and_more'),
        ('usuarios', '0004_usuariorol_usuario_rol_id_rol_52d79a_idx'),
    ]

    operations = [
        # Índices de Foreign Keys comentados porque ya existen en la base de datos.
        # Solo se mantiene el índice de 'nombre' que es un campo normal.
        migrations.AddIndex(
            model_name='corredora',
            index=models.Index(fields=['nombre'], name='corredora_nombre_c2ee43_idx'),
        ),
    ]
