# Generated by Django 5.2.6 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mercado_ix_mercado_pais_and_more'),
        ('corredoras', '0003_corredora_corredora_nombre_c2ee43_idx_and_more'),
        ('usuarios', '0005_usuariorol_ix_usuario_rol_rol'),
    ]

    operations = [
        # COMENTADO: Oracle crea automáticamente índices para Foreign Keys
        # Estos índices ya existen:
        # - CORREDORA_ID_PAIS_A50AD086 en corredora.id_pais
        # - CORREDORA__ID_CORREDO_BD8A263B en corredoraidentificador.id_corredora
        # - USUARIO_CO_ID_USUARIO_2166D2AF en usuariocorredora.id_usuario
        # - USUARIO_CO_ID_CORREDO_85F210F5 en usuariocorredora.id_corredora
        # migrations.AddIndex(
        #     model_name='corredora',
        #     index=models.Index(fields=['id_pais'], name='ix_corredora_pais'),
        # ),
        # migrations.AddIndex(
        #     model_name='corredoraidentificador',
        #     index=models.Index(fields=['id_corredora'], name='ix_ci_corredora'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_usuario'], name='usuario_cor_id_usua_6ed4c8_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='usuariocorredora',
        #     index=models.Index(fields=['id_corredora'], name='usuario_cor_id_corr_b32be7_idx'),
        # ),
    ]
