# Generated by Django 5.2.6 on 2025-11-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('emisor', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_mercado', models.ForeignKey(db_column='id_mercado', on_delete=django.db.models.deletion.RESTRICT, to='core.mercado')),
                ('id_moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.RESTRICT, to='core.moneda')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'instrumento',
            },
        ),
        migrations.CreateModel(
            name='EventoCapital',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('secuencia_evento', models.CharField(max_length=40)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_instrumento', models.ForeignKey(db_column='id_instrumento', on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumento')),
            ],
            options={
                'verbose_name': 'Evento de Capital',
                'verbose_name_plural': 'Eventos de Capital',
                'db_table': 'evento_capital',
            },
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['codigo'], name='instrumento_codigo_accfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['id_mercado'], name='instrumento_id_merc_bc708c_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['id_moneda'], name='instrumento_id_mone_c6288d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocapital',
            index=models.Index(fields=['id_instrumento'], name='evento_capi_id_inst_0e3d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocapital',
            index=models.Index(fields=['id_instrumento', 'secuencia_evento'], name='evento_capi_id_inst_5c9478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventocapital',
            unique_together={('id_instrumento', 'secuencia_evento')},
        ),
    ]
