# Generated by Django 5.2.6 on 2025-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['codigo'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
    ]
