# Generated by Django 5.2.6 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fuente_fuente_codigo_f64eab_idx_and_more'),
        ('instrumentos', '0002_alter_instrumento_options'),
    ]

    operations = [
        # TODOS los índices comentados porque Oracle ya los creó automáticamente:
        # - Foreign Keys → Oracle puede crear índices automáticamente
        # - Campos UNIQUE → Oracle crea índices únicos automáticamente
        # Si necesitas estos índices y NO existen, descomenta las líneas correspondientes
        # migrations.AddIndex(
        #     model_name='eventocapital',
        #     index=models.Index(fields=['id_instrumento'], name='evento_capi_id_inst_0e3d4e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='eventocapital',
        #     index=models.Index(fields=['id_instrumento', 'secuencia_evento'], name='evento_capi_id_inst_5c9478_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='instrumento',
        #     index=models.Index(fields=['codigo'], name='instrumento_codigo_accfc1_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='instrumento',
        #     index=models.Index(fields=['id_mercado'], name='instrumento_id_merc_bc708c_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='instrumento',
        #     index=models.Index(fields=['id_moneda'], name='instrumento_id_mone_c6288d_idx'),
        # ),
    ]
