# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mercado_mercado_id_pais_86cfe6_idx_and_more'),
        ('instrumentos', '0003_eventocapital_evento_capi_id_inst_0e3d4e_idx_and_more'),
    ]

    operations = [
        # NOTA: Si obtienes ORA-01408 o ORA-00955 al ejecutar migrate, significa que el índice ya existe
        # En ese caso, comenta el AddIndex correspondiente y vuelve a ejecutar migrate
        # Para usuarios nuevos (BD desde cero), estos índices se crearán automáticamente
        migrations.AddIndex(
            model_name='eventocapital',
            index=models.Index(fields=['id_instrumento'], name='evento_capi_id_inst_0e3d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['id_mercado'], name='instrumento_id_merc_bc708c_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['id_moneda'], name='instrumento_id_mone_c6288d_idx'),
        ),
    ]
