# Generated by Django 5.2.6 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mercado_ix_mercado_pais_and_more'),
        ('instrumentos', '0004_eventocapital_evento_capi_id_inst_0e3d4e_idx_and_more'),
    ]

    operations = [
        # COMENTADO: Oracle crea automáticamente índices para Foreign Keys
        # Estos índices ya existen automáticamente en Oracle
        # migrations.AddIndex(
        #     model_name='eventocapital',
        #     index=models.Index(fields=['id_instrumento'], name='ix_ev_instr'),
        # ),
        # migrations.AddIndex(
        #     model_name='instrumento',
        #     index=models.Index(fields=['id_mercado'], name='ix_instr_mercado'),
        # ),
        # migrations.AddIndex(
        #     model_name='instrumento',
        #     index=models.Index(fields=['id_moneda'], name='ix_instr_moneda'),
        # ),
    ]
