# Generated by Django 5.2.6 on 2025-11-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0005_eventocapital_ix_ev_instr_and_more'),
    ]

    operations = [
        # COMENTADO: Estos índices nunca se crearon porque las migraciones anteriores
        # estaban comentadas. Oracle crea automáticamente índices para Foreign Keys
        # con nombres diferentes, por lo que no hay nada que remover.
        # migrations.RemoveIndex(
        #     model_name='eventocapital',
        #     name='ix_ev_instr',
        # ),
        # migrations.RemoveIndex(
        #     model_name='instrumento',
        #     name='ix_instr_mercado',
        # ),
        # migrations.RemoveIndex(
        #     model_name='instrumento',
        #     name='ix_instr_moneda',
        # ),
    ]
