# Generated by Django 5.2.6 on 2025-11-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('corredoras', '0001_initial'),
        ('instrumentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('ejercicio', models.IntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('secuencia_evento', models.CharField(blank=True, max_length=40, null=True)),
                ('factor_actualizacion', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ingreso_por_montos', models.BooleanField(blank=True, null=True)),
                ('acogido_sfut', models.BooleanField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validada', 'Validada'), ('publicada', 'Publicada'), ('pendiente', 'Pendiente')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(db_column='actualizado_por', on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones_actualizadas', to='usuarios.usuario')),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones_creadas', to='usuarios.usuario')),
                ('id_corredora', models.ForeignKey(db_column='id_corredora', on_delete=django.db.models.deletion.RESTRICT, to='corredoras.corredora')),
                ('id_evento', models.ForeignKey(blank=True, db_column='id_evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrumentos.eventocapital')),
                ('id_fuente', models.ForeignKey(db_column='id_fuente', on_delete=django.db.models.deletion.RESTRICT, to='core.fuente')),
                ('id_instrumento', models.ForeignKey(db_column='id_instrumento', on_delete=django.db.models.deletion.RESTRICT, to='instrumentos.instrumento')),
                ('id_moneda', models.ForeignKey(db_column='id_moneda', on_delete=django.db.models.deletion.RESTRICT, to='core.moneda')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='FactorDef',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_factor', models.CharField(max_length=10, unique=True)),
                ('nombre_corto', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_valor', models.CharField(choices=[('factor', 'Factor'), ('monto', 'Monto'), ('tasa', 'Tasa')], default='factor', max_length=20)),
                ('orden_visual', models.IntegerField(blank=True, null=True)),
                ('aplica_en_suma', models.BooleanField(default=False)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factor',
                'verbose_name_plural': 'Factores',
                'db_table': 'factor_def',
                'indexes': [models.Index(fields=['codigo_factor'], name='factor_def_codigo__0ba846_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalificacionMontoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_monto', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_calificacion', models.ForeignKey(db_column='id_calificacion', on_delete=django.db.models.deletion.CASCADE, to='calificaciones.calificacion')),
                ('id_factor', models.ForeignKey(db_column='id_factor', on_delete=django.db.models.deletion.RESTRICT, to='calificaciones.factordef')),
            ],
            options={
                'verbose_name': 'Detalle Monto Calificación',
                'verbose_name_plural': 'Detalles Montos Calificaciones',
                'db_table': 'calificacion_monto_detalle',
            },
        ),
        migrations.CreateModel(
            name='CalificacionFactorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_calificacion', models.ForeignKey(db_column='id_calificacion', on_delete=django.db.models.deletion.CASCADE, to='calificaciones.calificacion')),
                ('id_factor', models.ForeignKey(db_column='id_factor', on_delete=django.db.models.deletion.RESTRICT, to='calificaciones.factordef')),
            ],
            options={
                'verbose_name': 'Detalle Factor Calificación',
                'verbose_name_plural': 'Detalles Factores Calificaciones',
                'db_table': 'calificacion_factor_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['id_corredora'], name='calificacio_id_corr_1bc757_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['id_instrumento'], name='calificacio_id_inst_e8fa74_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['id_fuente'], name='calificacio_id_fuen_1e31ab_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['id_evento'], name='calificacio_id_even_0855ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('id_corredora', 'id_instrumento', 'ejercicio', 'secuencia_evento')},
        ),
        migrations.AddIndex(
            model_name='calificacionmontodetalle',
            index=models.Index(fields=['id_calificacion'], name='calificacio_id_cali_38100d_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionmontodetalle',
            index=models.Index(fields=['id_factor'], name='calificacio_id_fact_33ab02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionmontodetalle',
            unique_together={('id_calificacion', 'id_factor')},
        ),
        migrations.AddIndex(
            model_name='calificacionfactordetalle',
            index=models.Index(fields=['id_calificacion'], name='calificacio_id_cali_004d35_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionfactordetalle',
            index=models.Index(fields=['id_factor'], name='calificacio_id_fact_d7c6fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionfactordetalle',
            unique_together={('id_calificacion', 'id_factor')},
        ),
    ]
