# Generated by Django 5.2.6 on 2025-11-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-creado_en', '-id_calificacion'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='factordef',
            options={'ordering': ['codigo_factor'], 'verbose_name': 'Factor', 'verbose_name_plural': 'Factores'},
        ),
        migrations.AddField(
            model_name='factordef',
            name='requerido',
            field=models.BooleanField(default=False),
        ),
    ]
