# Generated by Django 5.2.6 on 2025-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_alter_calificacion_options_alter_factordef_options_and_more'),
        ('core', '0003_fuente_fuente_codigo_f64eab_idx_and_more'),
        ('corredoras', '0001_initial'),
        ('instrumentos', '0003_eventocapital_evento_capi_id_inst_0e3d4e_idx_and_more'),
        ('usuarios', '0003_create_index_id_rol'),
    ]

    operations = [
        # TODOS los índices comentados porque Oracle ya los creó automáticamente:
        # - Foreign Keys → Oracle puede crear índices automáticamente
        # - Campos UNIQUE → Oracle crea índices únicos automáticamente
        # Si necesitas estos índices y NO existen, descomenta las líneas correspondientes
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_corredora'], name='calificacio_id_corr_1bc757_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_instrumento'], name='calificacio_id_inst_e8fa74_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_fuente'], name='calificacio_id_fuen_1e31ab_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_evento'], name='calificacio_id_even_0855ef_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionfactordetalle',
        #     index=models.Index(fields=['id_calificacion'], name='calificacio_id_cali_004d35_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionfactordetalle',
        #     index=models.Index(fields=['id_factor'], name='calificacio_id_fact_d7c6fb_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionmontodetalle',
        #     index=models.Index(fields=['id_calificacion'], name='calificacio_id_cali_38100d_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionmontodetalle',
        #     index=models.Index(fields=['id_factor'], name='calificacio_id_fact_33ab02_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='factordef',
        #     index=models.Index(fields=['codigo_factor'], name='factor_def_codigo__0ba846_idx'),
        # ),
    ]
