# Generated by Django 5.2.6 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_calificacion_calificacio_id_corr_1bc757_idx_and_more'),
        ('core', '0004_mercado_mercado_id_pais_86cfe6_idx_and_more'),
        ('corredoras', '0003_corredora_corredora_nombre_c2ee43_idx_and_more'),
        ('instrumentos', '0004_eventocapital_evento_capi_id_inst_0e3d4e_idx_and_more'),
        ('usuarios', '0004_usuariorol_usuario_rol_id_rol_52d79a_idx'),
    ]

    operations = [
        # Esta migración está vacía porque los índices ya existen en la base de datos.
        # Los índices están definidos en models.py para optimización de consultas,
        # pero fueron creados en migraciones anteriores o por otros medios.
        # Si necesitas recrear estos índices, crea una nueva migración con RunSQL.
    ]
