# Generated by Django 5.2.6 on 2025-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_calificacion_calificacio_id_corr_1bc757_idx_and_more'),
        ('core', '0005_mercado_ix_mercado_pais_and_more'),
        ('corredoras', '0004_corredora_ix_corredora_pais_and_more'),
        ('instrumentos', '0005_eventocapital_ix_ev_instr_and_more'),
        ('usuarios', '0005_usuariorol_ix_usuario_rol_rol'),
    ]

    operations = [
        # COMENTADO: Oracle crea automáticamente índices para Foreign Keys
        # Estos índices ya existen:
        # - CALIFICACI_ID_CORREDO_109CCC8C en id_corredora
        # - CALIFICACI_ID_INSTRUM_D39E870F en id_instrumento
        # - CALIFICACI_ID_FUENTE_2A67B60C en id_fuente
        # - CALIFICACI_ID_EVENTO_09E2591F en id_evento
        # - CALIFICACI_ID_CALIFIC_24D6D54E en calificacionfactordetalle.id_calificacion
        # - CALIFICACI_ID_FACTOR_A40BBB24 en calificacionfactordetalle.id_factor
        # - CALIFICACI_ID_CALIFIC_4C81A293 en calificacionmontodetalle.id_calificacion
        # - CALIFICACI_ID_FACTOR_3F49A4C6 en calificacionmontodetalle.id_factor
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_corredora'], name='ix_calif_corr'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_instrumento'], name='ix_calif_instr'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_fuente'], name='ix_calif_fuen'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacion',
        #     index=models.Index(fields=['id_evento'], name='ix_calif_evt'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionfactordetalle',
        #     index=models.Index(fields=['id_calificacion'], name='ix_cfd_calif'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionfactordetalle',
        #     index=models.Index(fields=['id_factor'], name='ix_cfd_factor'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionmontodetalle',
        #     index=models.Index(fields=['id_calificacion'], name='ix_cmd_calif'),
        # ),
        # migrations.AddIndex(
        #     model_name='calificacionmontodetalle',
        #     index=models.Index(fields=['id_factor'], name='ix_cmd_factor'),
        # ),
    ]
